### ISSUE TITLE
Port Vagrant to Containerlabs

### ISSUE THREAD

**Issue by mwindower** [metal-stack/mini-lab#71]
[Containerlab](https://github.com/srl-labs/containerlab) can be used to define our network topology as YAML file (comparable to docker-compose) and use docker images / VM images as nodes.

The VM part is mostly implemented in https://github.com/plajjan/vrnetlab where Cumulus support would be needed to be added.

**Comment by GrigoriyMikhalkin** [comment]
cc @mwindower, @majst01
The big problem that i encountered during migration(and still dealing with it) is that only Cumulus VX v4.x.x is available in containerized version. And i'm already facing some problems(with ansible setup) adapting it. For example, it looks like VRF management stuff behaves differently. Now, by default if we try to use `vrfInternet` it's always switching VRF to default one(`mgmt`), unless special flag `--no-vrf-switch` isn't specified.

Did we already looked into migrating to Cumulus v4.x.x? Asking that, just in case if someone is aware of big problems/blockers that can happen here.

**Comment by majst01** [comment]
We have been looking into Cumlus v4.x already and identified some issues. If it is possible to create our own Cumulus v3.7.x image, this would make the transition to containerlabs easier to understand and we dont have to update other components to match v4.x.x. But i have no Idea how difficult this might be.

In the midterm we have to migrate to Cumulus v4, longterm goal is to support  SONIC. This is the reason we want to move to a containerlabs based mini-lab, because with the Vagrant approach this might be difficult.

**Comment by mwennrich** [comment]
Biggest blocker I remember from my last tests with 4.x is, that we currently use static route leaking `vrf_route_leak_enable = TRUE` on the leafs, which is not available anymore in 4.x 
```
Cumulus Linux supports dynamic VRF route leaking. Static route leaking is not supported.
```
